#### Business Problem : To estimate the price of a house with the help of 2 models, i.e. Random Forest and Gradient Boosting

# Data Understanding

In [1]:
# Import the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.ensemble import GradientBoostingClassifier

In [2]:
# Import the dataset 
df = pd.read_csv('House_Pricing.csv')

In [3]:
df.head()

year_built  stories  num_bedrooms  full_bathrooms  half_bathrooms  \
0        1978        1             4               1               1   
1        1958        1             3               1               1   
2        2002        1             3               2               0   
3        2004        1             4               2               0   
4        2006        1             4               2               0   

   livable_sqft  total_sqft garage_type  garage_sqft  carport_sqft  \
0          1689        1859    attached          508             0   
1          1984        2002    attached          462             0   
2          1581        1578        none            0           625   
3          1829        2277    attached          479             0   
4          1580        1749    attached          430             0   

   has_fireplace  has_pool  has_central_heating  has_central_cooling  \
0           True     False                 True                 True   
1           True     False                 True                 True   
2          False     False                 True                 True   
3           True     False                 True                 True   
4           True     False                 True                 True   

   house_number       street_name  unit_number                city  zip_code  \
0         42670    Lopez Crossing          NaN            Hallfort     10907   
1          5194      Gardner Park          NaN            Hallfort     10907   
2          4366   Harding Islands          NaN  Lake Christinaport     11203   
3          3302  Michelle Highway          NaN  Lake Christinaport     11203   
4           582        Jacob Cape          NaN  Lake Christinaport     11203   

   sale_price  
0    270897.0  
1    302404.0  
2   2721596.0  
3    212968.0  
4    224529.0

In [4]:
# Remove the fields from the data set that we don't want to include in our model
df1 = df.drop(columns = ['house_number','street_name','unit_number','zip_code'])
df2 = df1

In [5]:
df1.head()

year_built  stories  num_bedrooms  full_bathrooms  half_bathrooms  \
0        1978        1             4               1               1   
1        1958        1             3               1               1   
2        2002        1             3               2               0   
3        2004        1             4               2               0   
4        2006        1             4               2               0   

   livable_sqft  total_sqft garage_type  garage_sqft  carport_sqft  \
0          1689        1859    attached          508             0   
1          1984        2002    attached          462             0   
2          1581        1578        none            0           625   
3          1829        2277    attached          479             0   
4          1580        1749    attached          430             0   

   has_fireplace  has_pool  has_central_heating  has_central_cooling  \
0           True     False                 True                 True   
1           True     False                 True                 True   
2          False     False                 True                 True   
3           True     False                 True                 True   
4           True     False                 True                 True   

                 city  sale_price  
0            Hallfort    270897.0  
1            Hallfort    302404.0  
2  Lake Christinaport   2721596.0  
3  Lake Christinaport    212968.0  
4  Lake Christinaport    224529.0

In [6]:
df.describe()

year_built       stories  num_bedrooms  full_bathrooms  \
count  42703.000000  42703.000000  42703.000000    42703.000000   
mean    1990.993209      1.365759      3.209283        1.923659   
std       19.199987      0.513602      1.043396        0.759699   
min     1852.000000      0.000000      0.000000        0.000000   
25%     1980.000000      1.000000      3.000000        1.000000   
50%     1994.000000      1.000000      3.000000        2.000000   
75%     2005.000000      2.000000      4.000000        2.000000   
max     2017.000000      4.000000     31.000000        8.000000   

       half_bathrooms  livable_sqft    total_sqft   garage_sqft  carport_sqft  \
count    42703.000000  42703.000000  42703.000000  42703.000000  42703.000000   
mean         0.527153   1987.758986   2127.155446    455.849800     41.656324   
std          0.499268    846.766270    922.807342    243.453463    168.715867   
min          0.000000     -3.000000      5.000000     -4.000000      0.000000   
25%          0.000000   1380.000000   1466.000000    412.000000      0.000000   
50%          1.000000   1808.000000   1937.000000    464.000000      0.000000   
75%          1.000000   2486.000000   2640.000000    606.000000      0.000000   
max          1.000000  12406.000000  15449.000000   8318.000000   9200.000000   

       house_number  unit_number      zip_code    sale_price  
count  42703.000000  3088.000000  42703.000000  4.270300e+04  
mean   18211.767347  2027.395402  11030.991476  4.419862e+05  
std    27457.109993  1141.383770    573.576228  3.442857e+05  
min        0.000000     3.000000  10004.000000  6.640000e+02  
25%      674.000000  1063.000000  10537.000000  2.855915e+05  
50%     4530.000000  2033.000000  11071.000000  4.021910e+05  
75%    24844.500000  2921.000000  11510.000000  5.327150e+05  
max    99971.000000  3998.000000  11989.000000  2.293578e+07

In [7]:
df1['sale_price'].min()

664.0

In [8]:
df1['sale_price'].max()

22935778.0

In [9]:
m = df1['sale_price'].mean()
m

441986.20551249327

In [10]:
df1['sale_price'] = df1['sale_price'] >= m

In [11]:
# Convert Y variable (Price) into 2 categories
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()

In [13]:
df1['sale_price'] = le.fit_transform(df1['sale_price'])
df1.head()

year_built  stories  num_bedrooms  full_bathrooms  half_bathrooms  \
0        1978        1             4               1               1   
1        1958        1             3               1               1   
2        2002        1             3               2               0   
3        2004        1             4               2               0   
4        2006        1             4               2               0   

   livable_sqft  total_sqft garage_type  garage_sqft  carport_sqft  \
0          1689        1859    attached          508             0   
1          1984        2002    attached          462             0   
2          1581        1578        none            0           625   
3          1829        2277    attached          479             0   
4          1580        1749    attached          430             0   

   has_fireplace  has_pool  has_central_heating  has_central_cooling  \
0           True     False                 True                 True   
1           True     False                 True                 True   
2          False     False                 True                 True   
3           True     False                 True                 True   
4           True     False                 True                 True   

                 city  sale_price  
0            Hallfort           0  
1            Hallfort           0  
2  Lake Christinaport           1  
3  Lake Christinaport           0  
4  Lake Christinaport           0

In [34]:
# Replace categorical data with one-hot encoded data
# • Garage type
# • city
from sklearn.preprocessing import LabelBinarizer
df_one_hot = df1.copy()
lb = LabelBinarizer()
lb_results = lb.fit_transform(df_one_hot['garage_type'])
lb_results_df = pd.DataFrame(lb_results, columns=lb.classes_)
lb_results_df.head()

attached  detached  none
0         1         0     0
1         1         0     0
2         0         0     1
3         1         0     0
4         1         0     0

In [15]:
final_df = pd.concat([df_one_hot,lb_results_df],axis = 1)

In [16]:
df_one_hot_en = final_df.copy()
lb_en = LabelBinarizer()
lb_results_en = lb_en.fit_transform(df_one_hot_en['city'])
lb_results_df_en = pd.DataFrame(lb_results_en, columns=lb_en.classes_)
lb_results_df_en.head()

Amystad  Brownport  Chadstad  Clarkberg  Coletown  Davidfort  Davidtown  \
0        0          0         0          0         0          0          0   
1        0          0         0          0         0          0          0   
2        0          0         0          0         0          0          0   
3        0          0         0          0         0          0          0   
4        0          0         0          0         0          0          0   

   East Amychester  East Janiceville  East Justin  ...  South Anthony  \
0                0                 0            0  ...              0   
1                0                 0            0  ...              0   
2                0                 0            0  ...              0   
3                0                 0            0  ...              0   
4                0                 0            0  ...              0   

   South Stevenfurt  Toddshire  Wendybury  West Ann  West Brittanyview  \
0                 0          0          0         0                  0   
1                 0          0          0         0                  0   
2                 0          0          0         0                  0   
3                 0          0          0         0                  0   
4                 0          0          0         0                  0   

   West Gerald  West Gregoryview  West Lydia  West Terrence  
0            0                 0           0              0  
1            0                 0           0              0  
2            0                 0           0              0  
3            0                 0           0              0  
4            0                 0           0              0  

[5 rows x 47 columns]

In [17]:
final_df_en = pd.concat([df_one_hot_en,lb_results_df_en],axis = 1)

In [18]:
print("Original dimensions :", df.shape)
print("One hot Encoded dimensions :", final_df_en.shape)
final_df_en.head()

Original dimensions : (42703, 20)
One hot Encoded dimensions : (42703, 66)


year_built  stories  num_bedrooms  full_bathrooms  half_bathrooms  \
0        1978        1             4               1               1   
1        1958        1             3               1               1   
2        2002        1             3               2               0   
3        2004        1             4               2               0   
4        2006        1             4               2               0   

   livable_sqft  total_sqft garage_type  garage_sqft  carport_sqft  ...  \
0          1689        1859    attached          508             0  ...   
1          1984        2002    attached          462             0  ...   
2          1581        1578        none            0           625  ...   
3          1829        2277    attached          479             0  ...   
4          1580        1749    attached          430             0  ...   

   South Anthony  South Stevenfurt  Toddshire  Wendybury West Ann  \
0              0                 0          0          0        0   
1              0                 0          0          0        0   
2              0                 0          0          0        0   
3              0                 0          0          0        0   
4              0                 0          0          0        0   

   West Brittanyview  West Gerald  West Gregoryview  West Lydia  West Terrence  
0                  0            0                 0           0              0  
1                  0            0                 0           0              0  
2                  0            0                 0           0              0  
3                  0            0                 0           0              0  
4                  0            0                 0           0              0  

[5 rows x 66 columns]

In [19]:
final_df_en.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42703 entries, 0 to 42702
Data columns (total 66 columns):
year_built              42703 non-null int64
stories                 42703 non-null int64
num_bedrooms            42703 non-null int64
full_bathrooms          42703 non-null int64
half_bathrooms          42703 non-null int64
livable_sqft            42703 non-null int64
total_sqft              42703 non-null int64
garage_type             42703 non-null object
garage_sqft             42703 non-null int64
carport_sqft            42703 non-null int64
has_fireplace           42703 non-null bool
has_pool                42703 non-null bool
has_central_heating     42703 non-null bool
has_central_cooling     42703 non-null bool
city                    42703 non-null object
sale_price              42703 non-null int64
attached                42703 non-null int32
detached                42703 non-null int32
none                    42703 non-null int32
Amystad                 42703 non-null

In [20]:
final_df_en = final_df_en.drop(columns =['garage_type','city'])

In [21]:
final_df_en.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42703 entries, 0 to 42702
Data columns (total 64 columns):
year_built              42703 non-null int64
stories                 42703 non-null int64
num_bedrooms            42703 non-null int64
full_bathrooms          42703 non-null int64
half_bathrooms          42703 non-null int64
livable_sqft            42703 non-null int64
total_sqft              42703 non-null int64
garage_sqft             42703 non-null int64
carport_sqft            42703 non-null int64
has_fireplace           42703 non-null bool
has_pool                42703 non-null bool
has_central_heating     42703 non-null bool
has_central_cooling     42703 non-null bool
sale_price              42703 non-null int64
attached                42703 non-null int32
detached                42703 non-null int32
none                    42703 non-null int32
Amystad                 42703 non-null int32
Brownport               42703 non-null int32
Chadstad                42703 non-null i

In [22]:
final_df_en['sale'] = final_df_en['sale_price']
final_df_en.head()

year_built  stories  num_bedrooms  full_bathrooms  half_bathrooms  \
0        1978        1             4               1               1   
1        1958        1             3               1               1   
2        2002        1             3               2               0   
3        2004        1             4               2               0   
4        2006        1             4               2               0   

   livable_sqft  total_sqft  garage_sqft  carport_sqft  has_fireplace  ...  \
0          1689        1859          508             0           True  ...   
1          1984        2002          462             0           True  ...   
2          1581        1578            0           625          False  ...   
3          1829        2277          479             0           True  ...   
4          1580        1749          430             0           True  ...   

   South Stevenfurt  Toddshire  Wendybury  West Ann  West Brittanyview  \
0                 0          0          0         0                  0   
1                 0          0          0         0                  0   
2                 0          0          0         0                  0   
3                 0          0          0         0                  0   
4                 0          0          0         0                  0   

   West Gerald  West Gregoryview  West Lydia  West Terrence  sale  
0            0                 0           0              0     0  
1            0                 0           0              0     0  
2            0                 0           0              0     1  
3            0                 0           0              0     0  
4            0                 0           0              0     0  

[5 rows x 65 columns]

In [23]:
final_df_en = final_df_en.drop(columns = ['sale_price'])

In [24]:
final_df_en.head()

year_built  stories  num_bedrooms  full_bathrooms  half_bathrooms  \
0        1978        1             4               1               1   
1        1958        1             3               1               1   
2        2002        1             3               2               0   
3        2004        1             4               2               0   
4        2006        1             4               2               0   

   livable_sqft  total_sqft  garage_sqft  carport_sqft  has_fireplace  ...  \
0          1689        1859          508             0           True  ...   
1          1984        2002          462             0           True  ...   
2          1581        1578            0           625          False  ...   
3          1829        2277          479             0           True  ...   
4          1580        1749          430             0           True  ...   

   South Stevenfurt  Toddshire  Wendybury  West Ann  West Brittanyview  \
0                 0          0          0         0                  0   
1                 0          0          0         0                  0   
2                 0          0          0         0                  0   
3                 0          0          0         0                  0   
4                 0          0          0         0                  0   

   West Gerald  West Gregoryview  West Lydia  West Terrence  sale  
0            0                 0           0              0     0  
1            0                 0           0              0     0  
2            0                 0           0              0     1  
3            0                 0           0              0     0  
4            0                 0           0              0     0  

[5 rows x 64 columns]

In [25]:
final_df_en = final_df_en.rename(columns = {'sale':'sale_price'})

In [26]:
final_df_en.head()

year_built  stories  num_bedrooms  full_bathrooms  half_bathrooms  \
0        1978        1             4               1               1   
1        1958        1             3               1               1   
2        2002        1             3               2               0   
3        2004        1             4               2               0   
4        2006        1             4               2               0   

   livable_sqft  total_sqft  garage_sqft  carport_sqft  has_fireplace  ...  \
0          1689        1859          508             0           True  ...   
1          1984        2002          462             0           True  ...   
2          1581        1578            0           625          False  ...   
3          1829        2277          479             0           True  ...   
4          1580        1749          430             0           True  ...   

   South Stevenfurt  Toddshire  Wendybury  West Ann  West Brittanyview  \
0                 0          0          0         0                  0   
1                 0          0          0         0                  0   
2                 0          0          0         0                  0   
3                 0          0          0         0                  0   
4                 0          0          0         0                  0   

   West Gerald  West Gregoryview  West Lydia  West Terrence  sale_price  
0            0                 0           0              0           0  
1            0                 0           0              0           0  
2            0                 0           0              0           1  
3            0                 0           0              0           0  
4            0                 0           0              0           0  

[5 rows x 64 columns]

In [27]:
final_df_en['has_fireplace'] = final_df_en['has_fireplace'].astype(int)

In [28]:
final_df_en['has_pool'] = final_df_en['has_pool'].astype(int)

In [29]:
final_df_en['has_central_heating'] = final_df_en['has_central_heating'].astype(int)

In [30]:
final_df_en['has_central_cooling'] = final_df_en['has_central_cooling'].astype(int)

In [31]:
final_df_en.head()

year_built  stories  num_bedrooms  full_bathrooms  half_bathrooms  \
0        1978        1             4               1               1   
1        1958        1             3               1               1   
2        2002        1             3               2               0   
3        2004        1             4               2               0   
4        2006        1             4               2               0   

   livable_sqft  total_sqft  garage_sqft  carport_sqft  has_fireplace  ...  \
0          1689        1859          508             0              1  ...   
1          1984        2002          462             0              1  ...   
2          1581        1578            0           625              0  ...   
3          1829        2277          479             0              1  ...   
4          1580        1749          430             0              1  ...   

   South Stevenfurt  Toddshire  Wendybury  West Ann  West Brittanyview  \
0                 0          0          0         0                  0   
1                 0          0          0         0                  0   
2                 0          0          0         0                  0   
3                 0          0          0         0                  0   
4                 0          0          0         0                  0   

   West Gerald  West Gregoryview  West Lydia  West Terrence  sale_price  
0            0                 0           0              0           0  
1            0                 0           0              0           0  
2            0                 0           0              0           1  
3            0                 0           0              0           0  
4            0                 0           0              0           0  

[5 rows x 64 columns]

In [32]:
final_df_en.dtypes

year_built              int64
stories                 int64
num_bedrooms            int64
full_bathrooms          int64
half_bathrooms          int64
livable_sqft            int64
total_sqft              int64
garage_sqft             int64
carport_sqft            int64
has_fireplace           int32
has_pool                int32
has_central_heating     int32
has_central_cooling     int32
attached                int32
detached                int32
none                    int32
Amystad                 int32
Brownport               int32
Chadstad                int32
Clarkberg               int32
Coletown                int32
Davidfort               int32
Davidtown               int32
East Amychester         int32
East Janiceville        int32
East Justin             int32
East Lucas              int32
Fosterberg              int32
Hallfort                int32
Jeffreyhaven            int32
                        ...  
Lake Carolyn            int32
Lake Christinaport      int32
Lake Dariu

In [35]:
# Apply Standard Scalar function to the Numerical Columns
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit(df[['livable_sqft','total_sqft','garage_sqft','carport_sqft']]))

StandardScaler(copy=True, with_mean=True, with_std=True)


In [36]:
print(scaler.transform(df[['livable_sqft','total_sqft','garage_sqft','carport_sqft']]))

[[-0.35282757 -0.29059     0.21421265 -0.24690512]
 [-0.00443928 -0.13562626  0.02526262 -0.24690512]
 [-0.48037311 -0.59509916 -1.87245288  3.45759125]
 ...
 [-1.64599767 -1.63541516 -1.87245288  0.92075214]
 [-0.69649195 -0.78690742 -0.22530155 -0.24690512]
 [-0.69294902 -0.78148911 -0.24583959 -0.24690512]]


# Modelling

In [37]:
# Create the X and y arrays
array = final_df_en.values
X = array[0:10000,1:63]

In [38]:
y = df['sale_price'][0:10000]

In [39]:
X

array([[1, 4, 1, ..., 0, 0, 0],
       [1, 3, 1, ..., 0, 0, 0],
       [1, 3, 2, ..., 0, 0, 0],
       ...,
       [1, 2, 1, ..., 0, 0, 0],
       [2, 3, 2, ..., 0, 0, 0],
       [3, 3, 2, ..., 0, 0, 0]], dtype=int64)

In [40]:
# Split the data set in a training set (70%) and a test set (30%)
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=7)

In [ ]:
final_df_en.head()

In [ ]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(random_state = 7)
regressor.fit(x_train,y_train)

In [ ]:
# Predicting the Test set results
y_pred = regressor.predict(x_test)

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

In [ ]:
from sklearn.metrics import make_scorer,mean_squared_error
from sklearn.model_selection import GridSearchCV
# Number of trees in random forest
# n_estimators = [500,1000,3000]
# Number of features to consider at every split
# max_features = [1.0, 0.3,0.1]
# Maximum number of levels in tree
# max_depth = [4,6]
# Minimum number of samples required at each leaf node
# min_samples_leaf = [3,5,9,17]
# Method of selecting samples for training each tree
# learning_rate = [1.0,0.05,0.02,0.01]
param_grid = { 
    'n_estimators': [500,1000],
    'max_features': [1.0,0.3,0.1],
    'max_depth' : [4,6],
    'min_samples_leaf' : [3,5,9,17]
}
grid = GridSearchCV(estimator = regressor,scoring = make_scorer(mean_squared_error), param_grid=param_grid,n_jobs = -1,cv = 4,
                    verbose = 2)
grid.fit(x_train,y_train)

In [ ]:
# Predicting the Test set results
y_pred1 = regressor.predict(x_test)

In [ ]:
best_accuracy = grid.best_score_
best_parameters = grid.best_params_
print(best_accuracy)
print(best_parameters)

In [ ]:
from sklearn.metrics import r2_score
# RMSE
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

In [ ]:
x = r2_score(y_test, y_pred1)
x

In [ ]:
# Fitting GBM to the Training set
classifier = GradientBoostingRegressor(random_state = 7)
classifier.fit(x_train, y_train)

In [ ]:
y_pred3 = classifier.predict(x_test)

In [ ]:
r2_score(y_test, y_pred3)

In [ ]:
param_grid = { 
    'n_estimators': [500,1000],
    'max_features': [1.0,0.3,0.1],
    'max_depth' : [4,6],
    'min_samples_leaf' : [3,5,9,17],
    'learning_rate' : [0.1, 0.05, 0.02, 0.01]
}
grid_gb = GridSearchCV(estimator = classifier,scoring = make_scorer(mean_squared_error), param_grid=param_grid,n_jobs = -1,cv = 2,
                      verbose = 2)
grid_gb.fit(x_train,y_train)

In [ ]:
best_accuracy_gb = grid_gb.best_score_
best_parameters_gb = grid_gb.best_params_
print(best_accuracy_gb)
print(best_parameters_gb)

In [ ]:
# Predicting the Test set results
y_pred4 = classifier.predict(x_test)
y_pred4

In [ ]:
from sklearn.externals import joblib 
  
# Save the model as a pickle in a file 
joblib.dump(regressor, 'House_Price_Estimation.pkl') 

In [ ]:
from sklearn import metrics
# RMSE
print(np.sqrt(metrics.mean_squared_error(y_test, y_pred1)))

In [ ]:
r2_score(y_test, y_pred4)

In [ ]:
# Training error
train_error = 1 - (regressor.score(x_train,y_train))

In [ ]:
train_error

In [ ]:
# Test error 
test_error = 1 - x
test_error

In [ ]:
df1.head()

In [ ]:
### Realtime predictions
Real_predictions_rf = regressor.predict([[5,10,15,23,21,26,12,30,8,20,28,17,19,29,31,35,37,38,36,43,45,46,41,49,40,50,25,20,13,23,
                                       65,14,78,15,43,12,45,47,49,1,12,19,10,18,59,56,15,23,27,54,52,53,59,50,44,46,78,74,42,5,
                                      75,72]])
Real_predictions_rf

In [ ]:
### Realtime predictions
Real_predictions_gb = classifier.predict([[5,10,15,23,21,26,12,30,8,20,28,17,19,29,31,35,37,38,36,43,45,46,41,49,40,50,25,20,13,23,
                                       65,14,78,15,43,12,45,47,49,1,12,19,10,18,59,56,15,23,27,54,52,53,59,50,44,46,78,74,42,5,
                                      75,72]])
Real_predictions_gb

In [ ]:
# Compute train and test errors
# from sklearn import linear_model
# alphas = np.logspace(0,100)
# enet = linear_model.ElasticNet(l1_ratio=0.7, max_iter=100)
# train_errors = list()
# test_errors = list()
# for alpha in alphas:
#     enet.set_params(alpha=alpha)
#     enet.fit(x_train, y_train)
#     train_errors.append(enet.score(x_train, y_train))
#     test_errors.append(enet.score(x_test, y_test))